/* ===========================================================================
   よく使う食品の見本帳 — 名前を打たずに選ぶだけで登録できるようにする。

   並びはカテゴリごと。絵文字は一覧で目を走らせるときの目印で、
   無い食品には同じ仲間の絵文字をあてている。

   商品データベースへの問い合わせはしない（仕様書2章）。
   ここにある分だけを端末が持ち、足りないものは手で足してもらう。
   =========================================================================== */

const FOOD_PRESETS = [
  /* --- 野菜 ------------------------------------------------------------- */
  { name: 'にんじん', category: 'VEGETABLE', icon: '🥕' },
  { name: 'じゃがいも', category: 'VEGETABLE', icon: '🥔' },
  { name: 'たまねぎ', category: 'VEGETABLE', icon: '🧅' },
  { name: 'キャベツ', category: 'VEGETABLE', icon: '🥬' },
  { name: 'レタス', category: 'VEGETABLE', icon: '🥬' },
  { name: 'はくさい', category: 'VEGETABLE', icon: '🥬' },
  { name: 'ほうれん草', category: 'VEGETABLE', icon: '🥬' , kana: 'ほうれんそう' },
  { name: '小松菜', category: 'VEGETABLE', icon: '🥬' , kana: 'こまつな' },
  { name: 'トマト', category: 'VEGETABLE', icon: '🍅' },
  { name: 'ミニトマト', category: 'VEGETABLE', icon: '🍅' },
  { name: 'きゅうり', category: 'VEGETABLE', icon: '🥒' },
  { name: 'なす', category: 'VEGETABLE', icon: '🍆' },
  { name: 'ピーマン', category: 'VEGETABLE', icon: '🫑' },
  { name: 'パプリカ', category: 'VEGETABLE', icon: '🫑' },
  { name: 'ブロッコリー', category: 'VEGETABLE', icon: '🥦' },
  { name: 'カリフラワー', category: 'VEGETABLE', icon: '🥦' },
  { name: 'だいこん', category: 'VEGETABLE', icon: '🥬' },
  { name: 'かぶ', category: 'VEGETABLE', icon: '🥬' },
  { name: 'ごぼう', category: 'VEGETABLE', icon: '🥕' },
  { name: 'れんこん', category: 'VEGETABLE', icon: '🥔' },
  { name: 'さつまいも', category: 'VEGETABLE', icon: '🍠' },
  { name: 'さといも', category: 'VEGETABLE', icon: '🥔' },
  { name: 'ながいも', category: 'VEGETABLE', icon: '🥔' },
  { name: 'かぼちゃ', category: 'VEGETABLE', icon: '🎃' },
  { name: 'ねぎ', category: 'VEGETABLE', icon: '🌿' },
  { name: '玉ねぎ（新）', category: 'VEGETABLE', icon: '🧅' , kana: 'しんたまねぎ' },
  { name: 'にら', category: 'VEGETABLE', icon: '🌿' },
  { name: 'にんにく', category: 'VEGETABLE', icon: '🧄' },
  { name: 'しょうが', category: 'VEGETABLE', icon: '🫚' },
  { name: 'もやし', category: 'VEGETABLE', icon: '🌱' },
  { name: 'えのき', category: 'VEGETABLE', icon: '🍄' },
  { name: 'しめじ', category: 'VEGETABLE', icon: '🍄' },
  { name: 'しいたけ', category: 'VEGETABLE', icon: '🍄' },
  { name: 'まいたけ', category: 'VEGETABLE', icon: '🍄' },
  { name: 'エリンギ', category: 'VEGETABLE', icon: '🍄' },
  { name: 'アスパラガス', category: 'VEGETABLE', icon: '🥬' },
  { name: 'オクラ', category: 'VEGETABLE', icon: '🥬' },
  { name: 'ズッキーニ', category: 'VEGETABLE', icon: '🥒' },
  { name: 'とうもろこし', category: 'VEGETABLE', icon: '🌽' },
  { name: 'えだまめ', category: 'VEGETABLE', icon: '🫛' },
  { name: 'いんげん', category: 'VEGETABLE', icon: '🫛' },
  { name: 'スナップえんどう', category: 'VEGETABLE', icon: '🫛' },
  { name: 'セロリ', category: 'VEGETABLE', icon: '🥬' },
  { name: '水菜', category: 'VEGETABLE', icon: '🥬' , kana: 'みずな' },
  { name: '春菊', category: 'VEGETABLE', icon: '🥬' , kana: 'しゅんぎく' },
  { name: 'サラダ用野菜', category: 'VEGETABLE', icon: '🥗' , kana: 'さらだようやさい' },
  { name: 'カットねぎ', category: 'VEGETABLE', icon: '🌿' },
  { name: 'アボカド', category: 'VEGETABLE', icon: '🥑' },

  /* --- 果物 ------------------------------------------------------------- */
  { name: 'りんご', category: 'FRUIT', icon: '🍎' },
  { name: 'みかん', category: 'FRUIT', icon: '🍊' },
  { name: 'バナナ', category: 'FRUIT', icon: '🍌' },
  { name: 'いちご', category: 'FRUIT', icon: '🍓' },
  { name: 'ぶどう', category: 'FRUIT', icon: '🍇' },
  { name: 'もも', category: 'FRUIT', icon: '🍑' },
  { name: 'なし', category: 'FRUIT', icon: '🍐' },
  { name: 'かき', category: 'FRUIT', icon: '🍊' },
  { name: 'キウイ', category: 'FRUIT', icon: '🥝' },
  { name: 'レモン', category: 'FRUIT', icon: '🍋' },
  { name: 'グレープフルーツ', category: 'FRUIT', icon: '🍊' },
  { name: 'メロン', category: 'FRUIT', icon: '🍈' },
  { name: 'すいか', category: 'FRUIT', icon: '🍉' },
  { name: 'パイナップル', category: 'FRUIT', icon: '🍍' },
  { name: 'さくらんぼ', category: 'FRUIT', icon: '🍒' },
  { name: 'ブルーベリー', category: 'FRUIT', icon: '🫐' },
  { name: 'マンゴー', category: 'FRUIT', icon: '🥭' },
  { name: 'カットフルーツ', category: 'FRUIT', icon: '🍓' },

  /* --- 肉・魚 ----------------------------------------------------------- */
  { name: '豚こま切れ肉', category: 'MEAT_FISH', icon: '🥩' , kana: 'ぶたこまぎれにく' },
  { name: '豚バラ肉', category: 'MEAT_FISH', icon: '🥓' , kana: 'ぶたばらにく' },
  { name: '豚ロース', category: 'MEAT_FISH', icon: '🥩' , kana: 'ぶたろーす' },
  { name: '豚ひき肉', category: 'MEAT_FISH', icon: '🥩' , kana: 'ぶたひきにく' },
  { name: '鶏むね肉', category: 'MEAT_FISH', icon: '🍗' , kana: 'とりむねにく' },
  { name: '鶏もも肉', category: 'MEAT_FISH', icon: '🍗' , kana: 'とりももにく' },
  { name: '鶏ささみ', category: 'MEAT_FISH', icon: '🍗' , kana: 'とりささみ' },
  { name: '鶏ひき肉', category: 'MEAT_FISH', icon: '🍗' , kana: 'とりひきにく' },
  { name: '手羽先', category: 'MEAT_FISH', icon: '🍗' , kana: 'てばさき' },
  { name: '牛こま切れ肉', category: 'MEAT_FISH', icon: '🥩' , kana: 'ぎゅうこまぎれにく' },
  { name: '牛ステーキ肉', category: 'MEAT_FISH', icon: '🥩' , kana: 'ぎゅうすてーきにく' },
  { name: '合いびき肉', category: 'MEAT_FISH', icon: '🥩' , kana: 'あいびきにく' },
  { name: 'ベーコン', category: 'MEAT_FISH', icon: '🥓' },
  { name: 'ハム', category: 'MEAT_FISH', icon: '🍖' },
  { name: 'ソーセージ', category: 'MEAT_FISH', icon: '🌭' },
  { name: '鮭', category: 'MEAT_FISH', icon: '🐟' , kana: 'さけ' },
  { name: 'さば', category: 'MEAT_FISH', icon: '🐟' },
  { name: 'さんま', category: 'MEAT_FISH', icon: '🐟' },
  { name: 'あじ', category: 'MEAT_FISH', icon: '🐟' },
  { name: 'ぶり', category: 'MEAT_FISH', icon: '🐟' },
  { name: 'たら', category: 'MEAT_FISH', icon: '🐟' },
  { name: 'まぐろ', category: 'MEAT_FISH', icon: '🍣' },
  { name: 'かつお', category: 'MEAT_FISH', icon: '🍣' },
  { name: '刺身', category: 'MEAT_FISH', icon: '🍣' , kana: 'さしみ' },
  { name: 'えび', category: 'MEAT_FISH', icon: '🦐' },
  { name: 'いか', category: 'MEAT_FISH', icon: '🦑' },
  { name: 'たこ', category: 'MEAT_FISH', icon: '🐙' },
  { name: 'あさり', category: 'MEAT_FISH', icon: '🦪' },
  { name: 'しらす', category: 'MEAT_FISH', icon: '🐟' },
  { name: 'ツナ缶', category: 'MEAT_FISH', icon: '🥫' , kana: 'つなかん' },

  /* --- 乳製品 ----------------------------------------------------------- */
  { name: '牛乳', category: 'DAIRY', icon: '🥛' , kana: 'ぎゅうにゅう' },
  { name: '低脂肪乳', category: 'DAIRY', icon: '🥛' , kana: 'ていしぼうにゅう' },
  { name: '豆乳', category: 'DAIRY', icon: '🥛' , kana: 'とうにゅう' },
  { name: 'ヨーグルト', category: 'DAIRY', icon: '🥛' },
  { name: '飲むヨーグルト', category: 'DAIRY', icon: '🥛' , kana: 'のむよーぐると' },
  { name: 'チーズ', category: 'DAIRY', icon: '🧀' },
  { name: 'スライスチーズ', category: 'DAIRY', icon: '🧀' },
  { name: 'ピザ用チーズ', category: 'DAIRY', icon: '🧀' , kana: 'ぴざようちーず' },
  { name: 'クリームチーズ', category: 'DAIRY', icon: '🧀' },
  { name: 'バター', category: 'DAIRY', icon: '🧈' },
  { name: 'マーガリン', category: 'DAIRY', icon: '🧈' },
  { name: '生クリーム', category: 'DAIRY', icon: '🥛' , kana: 'なまくりーむ' },

  /* --- 卵 --------------------------------------------------------------- */
  { name: '卵', category: 'EGG', icon: '🥚' , kana: 'たまご' },
  { name: 'うずら卵', category: 'EGG', icon: '🥚' , kana: 'うずらたまご' },
  { name: 'ゆで卵', category: 'EGG', icon: '🥚' , kana: 'ゆでたまご' },

  /* --- 加工食品 --------------------------------------------------------- */
  { name: '豆腐', category: 'PROCESSED', icon: '🍲' , kana: 'とうふ' },
  { name: '絹ごし豆腐', category: 'PROCESSED', icon: '🍲' , kana: 'きぬごしとうふ' },
  { name: '厚揚げ', category: 'PROCESSED', icon: '🍲' , kana: 'あつあげ' },
  { name: '油揚げ', category: 'PROCESSED', icon: '🍲' , kana: 'あぶらあげ' },
  { name: '納豆', category: 'PROCESSED', icon: '🫘' , kana: 'なっとう' },
  { name: 'こんにゃく', category: 'PROCESSED', icon: '🍲' },
  { name: 'しらたき', category: 'PROCESSED', icon: '🍜' },
  { name: 'かまぼこ', category: 'PROCESSED', icon: '🍥' },
  { name: 'ちくわ', category: 'PROCESSED', icon: '🍥' },
  { name: 'はんぺん', category: 'PROCESSED', icon: '🍥' },
  { name: 'さつま揚げ', category: 'PROCESSED', icon: '🍥' , kana: 'さつまあげ' },
  { name: '食パン', category: 'PROCESSED', icon: '🍞' , kana: 'しょくぱん' },
  { name: '菓子パン', category: 'PROCESSED', icon: '🥐' , kana: 'かしぱん' },
  { name: 'ロールパン', category: 'PROCESSED', icon: '🥐' },
  { name: 'ごはん（パック）', category: 'PROCESSED', icon: '🍚' },
  { name: 'うどん', category: 'PROCESSED', icon: '🍜' },
  { name: 'そば', category: 'PROCESSED', icon: '🍜' },
  { name: '中華麺', category: 'PROCESSED', icon: '🍜' , kana: 'ちゅうかめん' },
  { name: 'パスタ', category: 'PROCESSED', icon: '🍝' },
  { name: 'そうめん', category: 'PROCESSED', icon: '🍜' },
  { name: 'カップ麺', category: 'PROCESSED', icon: '🍜' , kana: 'かっぷめん' },
  { name: '餃子', category: 'PROCESSED', icon: '🥟' , kana: 'ぎょうざ' },
  { name: 'シュウマイ', category: 'PROCESSED', icon: '🥟' },
  { name: '惣菜', category: 'PROCESSED', icon: '🍱' , kana: 'そうざい' },
  { name: 'お弁当', category: 'PROCESSED', icon: '🍱' , kana: 'おべんとう' },
  { name: 'おにぎり', category: 'PROCESSED', icon: '🍙' },
  { name: 'サラダチキン', category: 'PROCESSED', icon: '🍗' },
  { name: 'キムチ', category: 'PROCESSED', icon: '🥬' },
  { name: '漬物', category: 'PROCESSED', icon: '🥒' , kana: 'つけもの' },
  { name: '梅干し', category: 'PROCESSED', icon: '🍙' , kana: 'うめぼし' },
  { name: '缶詰', category: 'PROCESSED', icon: '🥫' , kana: 'かんづめ' },
  { name: 'サバ缶', category: 'PROCESSED', icon: '🥫' , kana: 'さばかん' },
  { name: 'トマト缶', category: 'PROCESSED', icon: '🥫' , kana: 'とまとかん' },
  { name: 'コーン缶', category: 'PROCESSED', icon: '🌽' , kana: 'こーんかん' },
  { name: 'レトルトカレー', category: 'PROCESSED', icon: '🍛' },
  { name: 'シリアル', category: 'PROCESSED', icon: '🥣' },
  { name: '小麦粉', category: 'PROCESSED', icon: '🌾' , kana: 'こむぎこ' },
  { name: 'パン粉', category: 'PROCESSED', icon: '🍞' , kana: 'ぱんこ' },
  { name: '米', category: 'PROCESSED', icon: '🍚' , kana: 'こめ' },
  { name: 'もち', category: 'PROCESSED', icon: '🍡' },
  { name: '海苔', category: 'PROCESSED', icon: '🍙' , kana: 'のり' },
  { name: 'わかめ', category: 'PROCESSED', icon: '🌿' },
  { name: '乾物', category: 'PROCESSED', icon: '🌾' , kana: 'かんぶつ' },
  { name: 'お菓子', category: 'PROCESSED', icon: '🍪' , kana: 'おかし' },
  { name: 'チョコレート', category: 'PROCESSED', icon: '🍫' },
  { name: 'プリン', category: 'PROCESSED', icon: '🍮' },
  { name: 'ゼリー', category: 'PROCESSED', icon: '🍮' },
  { name: 'ケーキ', category: 'PROCESSED', icon: '🍰' },

  /* --- 冷凍食品 --------------------------------------------------------- */
  { name: '冷凍うどん', category: 'FROZEN', icon: '🍜' , kana: 'れいとううどん' },
  { name: '冷凍餃子', category: 'FROZEN', icon: '🥟' , kana: 'れいとうぎょうざ' },
  { name: '冷凍チャーハン', category: 'FROZEN', icon: '🍚' , kana: 'れいとうちゃーはん' },
  { name: '冷凍からあげ', category: 'FROZEN', icon: '🍗' , kana: 'れいとうからあげ' },
  { name: '冷凍コロッケ', category: 'FROZEN', icon: '🍘' , kana: 'れいとうころっけ' },
  { name: '冷凍野菜', category: 'FROZEN', icon: '🥦' , kana: 'れいとうやさい' },
  { name: '冷凍ブロッコリー', category: 'FROZEN', icon: '🥦' , kana: 'れいとうぶろっこりー' },
  { name: '冷凍ほうれん草', category: 'FROZEN', icon: '🥬' , kana: 'れいとうほうれんそう' },
  { name: '冷凍ミックスベジタブル', category: 'FROZEN', icon: '🥕' , kana: 'れいとうみっくすべじたぶる' },
  { name: '冷凍ごはん', category: 'FROZEN', icon: '🍚' , kana: 'れいとうごはん' },
  { name: '冷凍ピザ', category: 'FROZEN', icon: '🍕' , kana: 'れいとうぴざ' },
  { name: '冷凍パスタ', category: 'FROZEN', icon: '🍝' , kana: 'れいとうぱすた' },
  { name: 'アイスクリーム', category: 'FROZEN', icon: '🍨' },
  { name: '氷', category: 'FROZEN', icon: '🧊' , kana: 'こおり' },
  { name: '冷凍えび', category: 'FROZEN', icon: '🦐' , kana: 'れいとうえび' },

  /* --- 調味料 ----------------------------------------------------------- */
  { name: 'しょうゆ', category: 'SEASONING', icon: '🧂' },
  { name: 'みそ', category: 'SEASONING', icon: '🥣' },
  { name: '塩', category: 'SEASONING', icon: '🧂' , kana: 'しお' },
  { name: '砂糖', category: 'SEASONING', icon: '🧂' , kana: 'さとう' },
  { name: '酢', category: 'SEASONING', icon: '🧴' , kana: 'す' },
  { name: 'みりん', category: 'SEASONING', icon: '🧴' },
  { name: '料理酒', category: 'SEASONING', icon: '🧴' , kana: 'りょうりしゅ' },
  { name: 'サラダ油', category: 'SEASONING', icon: '🫗' , kana: 'さらだあぶら' },
  { name: 'ごま油', category: 'SEASONING', icon: '🫗' , kana: 'ごまあぶら' },
  { name: 'オリーブオイル', category: 'SEASONING', icon: '🫒' },
  { name: 'マヨネーズ', category: 'SEASONING', icon: '🧴' },
  { name: 'ケチャップ', category: 'SEASONING', icon: '🍅' },
  { name: 'ソース', category: 'SEASONING', icon: '🧴' },
  { name: 'ポン酢', category: 'SEASONING', icon: '🧴' , kana: 'ぽんず' },
  { name: 'めんつゆ', category: 'SEASONING', icon: '🧴' },
  { name: 'だしの素', category: 'SEASONING', icon: '🥣' , kana: 'だしのもと' },
  { name: 'コンソメ', category: 'SEASONING', icon: '🥣' },
  { name: '鶏がらスープの素', category: 'SEASONING', icon: '🥣' , kana: 'とりがらすーぷのもと' },
  { name: 'こしょう', category: 'SEASONING', icon: '🧂' },
  { name: 'カレールー', category: 'SEASONING', icon: '🍛' },
  { name: 'シチュールー', category: 'SEASONING', icon: '🍲' },
  { name: 'ドレッシング', category: 'SEASONING', icon: '🥗' },
  { name: '焼肉のたれ', category: 'SEASONING', icon: '🧴' , kana: 'やきにくのたれ' },
  { name: '味噌汁の素', category: 'SEASONING', icon: '🥣' , kana: 'みそしるのもと' },
  { name: 'わさび', category: 'SEASONING', icon: '🌿' },
  { name: 'からし', category: 'SEASONING', icon: '🌿' },
  { name: 'バジル', category: 'SEASONING', icon: '🌿' },
  { name: 'はちみつ', category: 'SEASONING', icon: '🍯' },
  { name: 'ジャム', category: 'SEASONING', icon: '🍓' },

  /* --- 飲料 ------------------------------------------------------------- */
  { name: '水', category: 'DRINK', icon: '💧' , kana: 'みず' },
  { name: '炭酸水', category: 'DRINK', icon: '🥤' , kana: 'たんさんすい' },
  { name: 'お茶', category: 'DRINK', icon: '🍵' , kana: 'おちゃ' },
  { name: '麦茶', category: 'DRINK', icon: '🍵' , kana: 'むぎちゃ' },
  { name: '緑茶', category: 'DRINK', icon: '🍵' , kana: 'りょくちゃ' },
  { name: 'コーヒー', category: 'DRINK', icon: '☕' },
  { name: '紅茶', category: 'DRINK', icon: '🍵' , kana: 'こうちゃ' },
  { name: 'オレンジジュース', category: 'DRINK', icon: '🧃' },
  { name: 'りんごジュース', category: 'DRINK', icon: '🧃' },
  { name: '野菜ジュース', category: 'DRINK', icon: '🧃' , kana: 'やさいじゅーす' },
  { name: 'スポーツドリンク', category: 'DRINK', icon: '🥤' },
  { name: 'ビール', category: 'DRINK', icon: '🍺' },
  { name: 'チューハイ', category: 'DRINK', icon: '🍹' },
  { name: 'ワイン', category: 'DRINK', icon: '🍷' },
  { name: '日本酒', category: 'DRINK', icon: '🍶' , kana: 'にほんしゅ' },
  { name: 'コーラ', category: 'DRINK', icon: '🥤' },

  /* --- その他 ----------------------------------------------------------- */
  { name: 'ペットフード', category: 'OTHER', icon: '🐾' },
  { name: '離乳食', category: 'OTHER', icon: '🍼' , kana: 'りにゅうしょく' },
  { name: 'サプリメント', category: 'OTHER', icon: '💊' },
  { name: '薬', category: 'OTHER', icon: '💊' , kana: 'くすり' },
];

/** 名前から見本帳を引く。手で打った名前にも絵文字を付けるために使う */
const FOOD_BY_NAME = FOOD_PRESETS.reduce((map, food) => {
  map[food.name] = food;
  return map;
}, {});

/**
 * 名前に合う絵文字。
 * 見本帳にそのものが無ければ、名前に含まれる語から仲間を探す。
 * 見つからなければ null を返し、呼び出し側は絵文字なしで描く。
 */
function iconForName(name) {
  if (FOOD_BY_NAME[name]) return FOOD_BY_NAME[name].icon;
  const hit = FOOD_PRESETS.find((food) => name.includes(food.name) || food.name.includes(name));
  return hit ? hit.icon : null;
}
